#!/bin/sh

SV_DIR=/etc/sv/

FCOPY_SERVICE=hv-fcopy-daemon
FCOPY_BIN=hv_fcopy_daemon

KVP_SERVICE=hv-kvp-daemon
KVP_BIN=hv_kvp_daemon

VSS_SERVICE=hv-vss-daemon
VSS_BIN=hv_vss_daemon

if grep -q hv_vmbus /proc/modules
then
  if [[ -f /usr/bin/${KVP_BIN} ]]
  then
      mkdir -p ${SV_DIR}/${KVP_SERVICE}
      echo -en "#!/bin/sh\nexec /usr/bin/${KVP_BIN} -n\n" > ${SV_DIR}/${KVP_SERVICE}/run
      chmod 0555 ${SV_DIR}/${KVP_SERVICE}/run
      ln -sf ${SV_DIR}/${KVP_SERVICE} /var/service
  fi
  if [[ -f /usr/bin/${FCOPY_BIN} ]]
  then
      mkdir -p ${SV_DIR}/${FCOPY_SERVICE}
      echo -en "#!/bin/sh\nif [ -e /dev/vmbus/hv_fcopy ];then\n exec /usr/bin/${FCOPY_BIN} -n\n\
else\n touch down\n sv stop ${FCOPY_SERVICE}\nfi" > ${SV_DIR}/${FCOPY_SERVICE}/run
      chmod 0555 ${SV_DIR}/${FCOPY_SERVICE}/run
      ln -sf ${SV_DIR}/${FCOPY_SERVICE} /var/service
  fi
  if [[ -f /usr/bin/${VSS_BIN} ]]
  then
      mkdir -p ${SV_DIR}/${VSS_SERVICE}
      # -e needs patch from #8236
      if $(${VSS_BIN} -h 2>&1 |grep -q '\-\-exclude\-loop'); then
          echo -en "#!/bin/sh\nexec /usr/bin/${VSS_BIN} -n -e\n" > ${SV_DIR}/${VSS_SERVICE}/run
      else
          echo -en "#!/bin/sh\nexec /usr/bin/${VSS_BIN} -n\n" > ${SV_DIR}/${VSS_SERVICE}/run
      fi
      chmod 0555 ${SV_DIR}/${VSS_SERVICE}/run
      ln -sf ${SV_DIR}/${VSS_SERVICE} /var/service
  fi

  # now set 'noop' scheduler for all block devices ...
  # See: projects/securepoint-utm/wiki/Hyper-V-Merkzettel#Linux-IO-Performance-Tweeks
  for device in /sys/block/sd[a-d]/queue/scheduler
  do
    echo noop > $device
  done
fi
