#!/bin/sh
RUNDIR=/var/run/
PIDFILE=${RUNDIR}/messagebus.pid
mkdir -p ${RUNDIR}/dbus
if [ -f ${PIDFILE} ]; then
  logger -t dbus-daemon -p daemon.info "removing stale pid file ${PIDFILE}"
  rm -f ${PIDFILE}
fi
exec dbus-daemon --system --nofork
