#!/bin/sh
. /etc/spconfig.sh
exec 2>&1
if [ -f env/USE_IPV6 ]; then
  read useipv6 < env/USE_IPV6
  if [ $useipv6 -eq 0 ]; then
    ARGS="-4"
  fi
fi

DNS_MANAGED_KEY_FILE="${SP_DNS_ROOT_DIR}/${SP_DNS_MANAGED_KEY_DIR}/managed-keys.bind"
grep -q "; placeholder" ${DNS_MANAGED_KEY_FILE} && rm ${DNS_MANAGED_KEY_FILE} ${DNS_MANAGED_KEY_FILE}.jnl
exec /usr/sbin/named $ARGS -t ${SP_DNS_ROOT_DIR} -c /named.conf -f -u ${SP_DNS_USER}
