#!/bin/sh
exec 2>&1
read ULIMITN < /etc/squid/ULIMITN
# prevent ULIMITN causing segmentation faults in combination with a 
# SQUID_MAXFD that is set to low, see #7749
if [ $ULIMITN -lt 4096 ]; then
  ULIMITN=4096
fi
if [ $ULIMITN -gt 8192 ]; then
  ULIMITN=8192
fi

# See #11988
ARGS=""
# security_file_certgen comes only with squid 4
if [ -x /usr/libexec/squid/security_file_certgen ]; then
  ARGS="--foreground"
else
  ARGS="-N"
fi

ulimit -HS -n $ULIMITN
exec /usr/sbin/squid -n rproxy -s ${ARGS} -f /etc/squid/squid-reverse.conf
