#!/bin/sh
. /etc/functions.sh
exec 1>&2
daemon_directory=/usr/libexec/postfix \
command_directory=/usr/sbin \
config_directory=/etc/postfix \
queue_directory=/data/mail/mqeue \
mail_owner=postfix \
setgid_group=postdrop \
 /usr/sbin/postfix check || exit 1

exec /usr/libexec/postfix/master
