#!/bin/sh
exec chpst -u daemon \
  nice -n 15 /usr/bin/fetchmail \
  --pidfile /var/run/fetchmail/fetchmail.pid \
  --idfile /data/fetchmail/idfile \
  -N \
  --syslog \
  --smtphost 127.0.0.2 \
  -f /etc/fetchmail.conf
