#!/bin/sh
exec 2>&1
SYSCONF=/data/securepoint/etc
KEYFILE=${SYSCONF}/dropbear-rsa.key
LASTLOG=/var/log/lastlog

[ -f $LASTLOG ] || touch $LASTLOG

if [ ! -f ${KEYFILE} ]
then
  mkdir -p ${SYSCONF} || KEYFILE=/tmp/dropbear-rsa-temp.key
  dropbearkey -t rsa -f ${KEYFILE} > /dev/null
fi
exec dropbear -g -F -E -p 22 -r ${KEYFILE}
